language: java
jdk:
- oraclejdk7
before_install:
- echo $GPG_KEY > tmp.txt && gpg --batch --passphrase-fd 3 3<tmp.txt secret.gpg.gpg
script: mvn verify -Prelease -Dhp.iod.apiKey=$API_KEY -Dhp.dev.iod.apiKey=$DEV_API_KEY
after_success: bash travis.sh
env:
  global:
  # SONATYPE_USERNAME
  - secure: j4wCbNIj62CKJ39mMJumbPz9NFF8HMQKLVehO9Naq4HtX9IbR0XEv2nYa2ldaIM5Gi3Ki2ikHHZRx+OOnapWjthRWhW0dzNzqdGfAi1heOHB9xLT1xYjS1PiscI88+ip1s8Hc4b0A8v0FSQRa+QtzIoX9srpQiUHwEzXGsunz+E=
  # SONATYPE_PASSWORD
  - secure: SeLijG5ju4hzdoz96irT4LvfRLpQk/4B25NMKME9tRgo9Oz61WgrFmm08iuft1NeLT36jDeHl1uEhYx3VJlHfFSueFw1emX2HLTazyAOfl7Ip/5g0DW04AmSYAJnA8RyoP24fE3qib8Uby8YoddUdJot5gMV1aqh0KuV9jBV+Ho=
  # GPG_PASSPHRASE
  - secure: FC1sR0dbWExJZERAAk6+4I028JRpW29tY8ngq7fWNPDW67gfvxXHAPV6SpJP6awMu0CRdKg8ANTinM+3AMxXEuKXeJTScVKdzwdoQzLru1toKypor4NrjnBck+i8gHP36BgvJo7YEfspaTRTILyYYTITmYTMK8xic7LIKrSu2GI=
  # GPG_KEYID
  - secure: F5TjiUeX2mnv1wcvowQCfLoiuMutIcurgVqxnrCto08RCx7BU5KYhoK9f/j1kI4lNkrhGcHoXy4L+PMwmM94Q7LHbhurBiTcVmOV8tq9isVS8bZXqdw23TyabrXEmIc2LXD7eJhzXX3LXxLg2RUaJAsAvAAxfcOinHuzppJ5z/8=
  # GPG_KEY
  - secure: ls2sWTc2D6m4rqzu+aIqk2KscWsm2FRbEowez0kRuosW5An/BrjjCFGYVNzovgMMCfnwdNrVlDEgN9jyUUSfZS+zpZmvqi5+OwGnFOi5BhdAq/DvNOi8+2x95dJ7EWHNiowfR8b3PsA4AWvfZfthyDE4B7YZ2UQxbDlht5vujh8=
  # API_KEY
  - secure: XD7/u+zC3hO4Nj9fMjg6YrIBFxcqrbkOGpK96NKy2op9Pkc3R/OaDQAI33mD27yMkdNgspL4Cu8xmEy8496yxWkPPLMfeEJJoC64wRkALN9nbwhMssQh/f1fe7oL71bsdwt0Da9k+Wlsokx6thXmYOtdWS5SKd+ISC7PzhiEIKY=
  # DEV_API_KEY
  - secure: BTkzfC47geKHM/e0xSTPVzmR/Zgjke288lrPVHyyv3hb61Vilzp0WGA8kDlc47kdUyPBzVfvVCRa/zr0ba2VaTnhn8jn8ApPz6cpngWJumnPjky5vfRV/XYx+8QtiVj8ED6csuACa/LPbbzLHnkAMLUe42yRUnL3pJbfrJf3uuM=
  # GITHUB_TOKEN
  - secure: jciupo3CbAcfu4Ml8ULHQtD2ih1c74e1eA8iAi9wRl0CQGR3a6pgB2rhmrRore5QOUoPOLc5kjRpamPG7G7u7EsqRKNfDRZ4RpCPkExMsLQcgi1Ayh4uxPF2t0/7i+LaRgjsG6cOjsFnHQWTC6UzXYaemCUEWKB65Uki8l7ky9w=
